# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b88087fc0df3b3a8cf028e9b83d2ddbb2deebe79e009fd4296b6286c2034ba916230acf120e21ad7e5a25fe7cac98a06c44343518a31fdfb1cfe167d6fe0d869

test:
  secret_key_base: 4362a8f140b3a3185db2222037e96b962ee8463775ba892e132155b9bd46eb44d4ecfd87052ea760babf75afecd863ad68fae75620b36901335b26f3c681c529

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
